image: node:lts

stages:
  - test
  - build

audit:
  stage: test
  script:
    - cd src/server
    - npm audit
  allow_failure: true
  only:
    - merge_requests
    - master

lint-client:
  stage: test
  script:
    - cd src/client
    - npm install
    - npm run lint
  only:
    - merge_requests
    - master

lint-server:
  stage: test
  script:
    - cd src/server
    - npm install
    - npm run lint
  only:
    - merge_requests
    - master

build-image-latest:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  variables:
    #IMAGE_TAG_REF: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    #IMAGE_TAG_ALIAS: $CI_REGISTRY_IMAGE:latest
    IMAGE_TAG_REF: isleward/isleward:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_ALIAS: isleward/isleward:latest
  script:
    - docker pull $IMAGE_TAG_ALIAS || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_ALIAS -t $IMAGE_TAG_REF -t $IMAGE_TAG_ALIAS .
    - docker push $IMAGE_TAG_REF
    - docker push $IMAGE_TAG_ALIAS
  rules:
    - when: never

build-image-stable:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  variables:
    #IMAGE_TAG_REF: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    #IMAGE_TAG_ALIAS: $CI_REGISTRY_IMAGE:stable
    IMAGE_TAG_REF: isleward/isleward:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_ALIAS: isleward/isleward:stable
  script:
    - docker pull $IMAGE_TAG_ALIAS || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_ALIAS -t $IMAGE_TAG_REF -t $IMAGE_TAG_ALIAS .
    - docker push $IMAGE_TAG_REF
    - docker push $IMAGE_TAG_ALIAS
  rules:
    - when: never

build-static-server-image-latest:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  variables:
    IMAGE_TAG_REF: isleward/isleward-static:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_ALIAS: isleward/isleward-static:latest
  script:
    - docker pull $IMAGE_TAG_ALIAS || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_ALIAS -f src/rust-server.Dockerfile -t $IMAGE_TAG_REF -t $IMAGE_TAG_ALIAS src/
    - docker push $IMAGE_TAG_REF
    - docker push $IMAGE_TAG_ALIAS
  rules:
    - when: never

build-static-server-image-stable:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  variables:
    IMAGE_TAG_REF: isleward/isleward-static:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_ALIAS: isleward/isleward-static:stable
  script:
    - docker pull $IMAGE_TAG_ALIAS || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_ALIAS -f src/rust-server.Dockerfile -t $IMAGE_TAG_REF -t $IMAGE_TAG_ALIAS src/
    - docker push $IMAGE_TAG_REF
    - docker push $IMAGE_TAG_ALIAS
  rules:
    - when: never
